### ISSUE TITLE
stl issues

### ISSUE THREAD

**Issue by FS-Far-Star** [shrey16/caustic_based_surface_generation#4]
Hi,
I am not entirely sure whether it's my stl viewer or the stl themselves. I used paint 3d and github's built in stl display to check the stl files you included, there are a lot of voids in the mesh... Checked the raw data with a wireframe plot, that looks good. I have a piece of code that packs the data into stl with numpy-stl, but that's packing it into a solid (rather than a surface). Do you know if material is meant to be added below the surface (in z-direction, or the h variable as used in the code), or above? 
Thanks

**Comment by shrey16** [comment]
Hey,

I am sorry I cannot help you simply because I do not remember anything
about this anymore. This was years ago as a project in a college course. I
really do not have the time to go into this again and break down all the
code, it was a huge hassle to write it in the first place. Sorry I couldn't
help you anymore than this.

Shrey

**Comment by FS-Far-Star** [comment]
Thanks for reply, totally understandable as this was ages ago. Good luck with whatever you are doing now mate:)
